### ISSUE TITLE
demo.sh install returns no matches for kind "Task" in version "tekton.dev/v1beta1" errors

### ISSUE THREAD

**Issue by craq2017** [siamaksade/tekton-cd-demo#5]
unable to recognize "tasks/dependency-report-task.yaml": no matches for kind "Task" in version "tekton.dev/v1beta1"
unable to recognize "tasks/deploy-app-task.yaml": no matches for kind "Task" in version "tekton.dev/v1beta1"
unable to recognize "tasks/gatling-task.yaml": no matches for kind "Task" in version "tekton.dev/v1beta1"
unable to recognize "tasks/mvn-task.yaml": no matches for kind "Task" in version "tekton.dev/v1beta1"
unable to recognize "tasks/oc-task.yaml": no matches for kind "Task" in version "tekton.dev/v1beta1"

**Comment by siamaksade** [comment]
Pipeline Operator doesn't seem to have been installed correctly and therefore `Task` CRs are not recognized
